###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID ece-rh810-8)
#  Generated on:      Mon Dec  2 16:41:55 2024
#  Design:            nbit_stack
#  Command:           saveDesign nbit_stack_FINAL.enc.dat
###############################################################
current_design nbit_stack
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 0.976000 -waveform {0.000000 0.488000}
set_propagated_clock  [get_ports {clk}]
set_wire_load_mode enclosed
set_input_delay -add_delay 0 -clock [get_clocks {clk}] [get_ports {reset}]
