###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID ece-rh810-22)
#  Generated on:      Tue Oct 29 16:22:08 2024
#  Design:            recognizer
#  Command:           saveIoFile -locations recognizer.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
    (left
	(pin name="clk"	offset=5.4150 layer=1 width=0.0600 depth=0.3350 place_status=placed  )
	(pin name="reset"	offset=7.5050 layer=1 width=0.0600 depth=0.3350 place_status=placed  )
	(pin name="x"	offset=9.5950 layer=1 width=0.0600 depth=0.3350 place_status=placed  )
    )
    (right
	(pin name="y"	offset=7.6950 layer=1 width=0.0600 depth=0.3350 place_status=placed  )
    )
)
