###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID ece-rh810-22)
#  Generated on:      Tue Oct 29 16:22:08 2024
#  Design:            recognizer
#  Command:           saveIoFile -locations recognizer.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
(left
        
       
        (   pin name="push"       offset=60.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
           (pin name="pop"        offset=100.0  layer=1 width=0.0600 depth=0.3350 place_status=placed)
           (pin name="clk"        offset=140.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="data_in[0]"  offset=180.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="data_in[1]"  offset=190.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="data_in[2]"  offset=200.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="data_in[3]"  offset=210.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
       )
(bottom 
            (pin name="scan_in[0]"  offset=60.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_in[1]"  offset=65.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_in[2]"  offset=70.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_in[3]"  offset=75.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="test_mode"   offset=130.0  layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="reset"      offset=160.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
) 
    (right
        (pin name="data_out[0]" offset=25.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
        (pin name="data_out[1]" offset=35.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
        (pin name="data_out[2]" offset=45.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
        (pin name="data_out[3]" offset=55.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
        (pin name="full"       offset=100.0   layer=1 width=0.0600 depth=0.3350 place_status=placed)
        (pin name="null"       offset=130.0   layer=1 width=0.0600 depth=0.3350 place_status=placed) 
            (pin name="scan_out[0]"  offset=180.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_out[1]"  offset=190.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_out[2]"  offset=200.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
            (pin name="scan_out[3]"  offset=210.0 layer=1 width=0.0600 depth=0.3350 place_status=placed)
    )

)


