`timescale 1ns / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Oct 29 2024 19:41:23 EDT (Oct 29 2024 23:41:23 UTC)

// Verification Directory fv/recognizer 

module recognizer(clk, reset, x, y);
  input clk, reset, x;
  output y;
  wire clk, reset, x;
  wire y;
  wire [1:0] state;
  wire n_0, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_21, n_22;
  DFFRHQX1 \state_reg[0] (.RN (1'b1), .CK (clk), .D (n_14), .Q
       (state[0]));
  DFFRHQX1 \state_reg[1] (.RN (1'b1), .CK (clk), .D (n_15), .Q
       (state[1]));
  NAND2X1 g560__2398(.A (n_11), .B (n_12), .Y (n_15));
  NAND2X1 g561__5107(.A (n_13), .B (n_10), .Y (n_14));
  NAND2X1 g562__6260(.A (state[1]), .B (n_6), .Y (n_13));
  NAND2X1 g563__4319(.A (n_3), .B (n_8), .Y (n_12));
  NAND2X1 g564__8428(.A (state[0]), .B (n_9), .Y (n_11));
  NAND2X1 g568__5526(.A (n_5), .B (n_4), .Y (n_10));
  NOR2X1 g565__6783(.A (n_7), .B (state[1]), .Y (n_9));
  NOR2X1 g566__3680(.A (n_7), .B (n_22), .Y (n_8));
  NOR2X1 g567__1617(.A (n_7), .B (state[0]), .Y (n_6));
  NOR2X1 g569__2802(.A (x), .B (n_0), .Y (n_5));
  NAND2X1 g570__1705(.A (state[1]), .B (n_3), .Y (n_4));
  NOR2X1 g571__5122(.A (n_3), .B (n_21), .Y (y));
  NAND2X1 g572__8246(.A (x), .B (reset), .Y (n_7));
  INVX1 g573(.A (state[0]), .Y (n_3));
  INVX1 g575(.A (reset), .Y (n_0));
  INVX1 fopt1(.A (state[1]), .Y (n_21));
  INVX1 fopt2(.A (state[1]), .Y (n_22));
endmodule

