/*
###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID ece-rh810-8)
#  Generated on:      Tue Nov  5 18:06:49 2024
#  Design:            recognizer
#  Command:           saveNetlist /home/shivansa/CUSTOM-CIRCUIT-DESIGN/HW4_shivansa/Innovus/Run2_OutputFiles/Route/Recognizer_Routed_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Oct 29 2024 19:41:23 EDT (Oct 29 2024 23:41:23 UTC)
// Verification Directory fv/recognizer 
module recognizer (
	clk, 
	reset, 
	x, 
	y);
   input clk;
   input reset;
   input x;
   output y;

   // Internal wires
   wire FE_DBTN0_state_1;
   wire [1:0] state;
   wire n_0;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;

   INVX1 FE_DBTC0_state_1 (.Y(FE_DBTN0_state_1),
	.A(state[1]));
   DFFRHQX1 \state_reg[0]  (.Q(state[0]),
	.D(n_14),
	.RN(1'b1),
	.CK(clk));
   DFFRHQX1 \state_reg[1]  (.Q(state[1]),
	.D(n_15),
	.RN(1'b1),
	.CK(clk));
   NAND2X1 g560__2398 (.Y(n_15),
	.A(n_11),
	.B(n_12));
   NAND2X1 g561__5107 (.Y(n_14),
	.A(n_13),
	.B(n_10));
   NAND2X1 g562__6260 (.Y(n_13),
	.A(state[1]),
	.B(n_6));
   NAND2X1 g563__4319 (.Y(n_12),
	.A(n_3),
	.B(n_8));
   NAND2X1 g564__8428 (.Y(n_11),
	.A(state[0]),
	.B(n_9));
   NAND2X1 g568__5526 (.Y(n_10),
	.A(n_5),
	.B(n_4));
   NOR2X1 g565__6783 (.Y(n_9),
	.A(n_7),
	.B(state[1]));
   NOR2X1 g566__3680 (.Y(n_8),
	.A(n_7),
	.B(FE_DBTN0_state_1));
   NOR2X1 g567__1617 (.Y(n_6),
	.A(n_7),
	.B(state[0]));
   NOR2X1 g569__2802 (.Y(n_5),
	.A(x),
	.B(n_0));
   NAND2X1 g570__1705 (.Y(n_4),
	.A(state[1]),
	.B(n_3));
   NOR2X1 g571__5122 (.Y(y),
	.A(n_3),
	.B(FE_DBTN0_state_1));
   NAND2X1 g572__8246 (.Y(n_7),
	.A(x),
	.B(reset));
   INVX1 g573 (.Y(n_3),
	.A(state[0]));
   INVX1 g575 (.Y(n_0),
	.A(reset));
endmodule

